revert some dependency upgrades
Unfortunately some dependency upgrade causes requests against the runtime to
fail sporadically with log/output.

2022-02-01 14:00:43 +0000] [10] [WARNING] Invalid HTTP request received.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 132, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered

Until it is clear which dependencies exactly cause this, we revert most of the upgrades.